# Generated by Django 5.2 on 2025-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeExame', models.CharField(max_length=100, verbose_name='Nome do Exame')),
                ('dataRealizacao', models.DateField(verbose_name='Data de Realização')),
                ('resultado', models.TextField(verbose_name='Resultado do Exame')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exame',
                'ordering': ['id'],
            },
        ),
    ]
