# Generated by Django 5.2 on 2025-06-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='dataEmissao',
        ),
    ]
