# Generated by Django 5.2 on 2025-06-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissonalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('dataNascimento', models.DateField(max_length=100, verbose_name='Data de Nascimento')),
                ('registroConselho', models.CharField(max_length=20, unique=True, verbose_name='Registro no Conselho')),
                ('especialidade', models.CharField(max_length=50, verbose_name='Especialidade')),
                ('tipoProfissional', models.CharField(choices=[('Medico', 'Médico'), ('Enfermeiro', 'Enfermeiro'), ('Fisioterapeuta', 'Fisioterapeuta'), ('Psicologo', 'Psicólogo'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Profissional')),
            ],
            options={
                'verbose_name': 'Profissional de Saúde',
                'verbose_name_plural': 'Profissionais de Saúde',
                'ordering': ['id'],
            },
        ),
    ]
